apiVersion: v1
kind: Pod
metadata: 
  name: my-pod1
spec:
  containers: 
    - name: my-container1
      image: n91k16/myapp:latest
      ports: 
        - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata: 
  name: my-pod2
spec:
  containers: 
    - name: my-container2
      image: n91k16/myapp:latest
      ports: 
        - containerPort: 80